CUSTOM_NAME="keryx-miner-v0.1.4.7-OPoI"
CUSTOM_VERSION="0.1.4.7"
CUSTOM_ALGO="keryxhash"
CUSTOM_COIN="KRX"
CUSTOM_LOG_BASENAME="keryx-miner"
CUSTOM_CONFIG_FILENAME="config.ini"
CUSTOM_CONFIG_PARSER="h-config.sh"
CUSTOM_MINER_BIN="keryx-miner"
CUSTOM_MINER_API_PORT="4068"
